import PDFDocument from "pdfkit";
import { MonthlySalaryRecord } from "../models/MonthlySalaryRecord.js";
import { User } from "../models/User.js";

export async function downloadPayslip(req, res) {
  const { id } = req.params;
  const rec = await MonthlySalaryRecord.findById(id).populate("userId", "name email role");
  if (!rec) return res.status(404).json({ message: "Record not found" });

  const requester = req.user;
  const ownerId = rec.userId._id?.toString?.() || rec.userId.toString();
  if (requester.role !== "admin" && ownerId !== requester._id.toString()) {
    return res.status(403).json({ message: "Forbidden" });
  }

  const user = await User.findById(rec.userId);
  const monthName = new Date(Date.UTC(rec.year, rec.month - 1, 1)).toLocaleString("en", {
    month: "long",
    year: "numeric",
  });

  res.setHeader("Content-Type", "application/pdf");
  res.setHeader(
    "Content-Disposition",
    `attachment; filename="payslip-${user?.email || "employee"}-${rec.year}-${rec.month}.pdf"`
  );

  const doc = new PDFDocument({ margin: 50 });
  doc.pipe(res);

  doc.fontSize(20).text("Payslip", { align: "center" });
  doc.moveDown();
  doc.fontSize(12).text(`Employee: ${user?.name || ""}`);
  doc.text(`Email: ${user?.email || ""}`);
  doc.text(`Period: ${monthName}`);
  doc.moveDown();
  doc.text(`Base salary: ${rec.baseSalary.toFixed(2)}`);
  doc.moveDown(0.5);
  doc.fontSize(11).text("Deductions:", { underline: true });
  if (!rec.deductions?.length) {
    doc.text("None");
  } else {
    for (const d of rec.deductions) {
      doc.text(`- ${d.label}: ${d.amount.toFixed(2)}`);
    }
  }
  doc.moveDown();
  doc.fontSize(12).text(`Total deductions: ${rec.totalDeductions.toFixed(2)}`);
  doc.fontSize(14).text(`Net salary: ${rec.netSalary.toFixed(2)}`, { underline: true });
  doc.moveDown(2);
  doc.fontSize(9).fillColor("#666").text("Generated by Office Portal. Amounts follow admin-configured rules.", {
    align: "center",
  });

  doc.end();
}

export async function viewPayslipJson(req, res) {
  const { id } = req.params;
  const rec = await MonthlySalaryRecord.findById(id).populate("userId", "name email");
  if (!rec) return res.status(404).json({ message: "Record not found" });
  const ownerId = rec.userId._id?.toString?.() || rec.userId.toString();
  if (req.user.role !== "admin" && ownerId !== req.user._id.toString()) {
    return res.status(403).json({ message: "Forbidden" });
  }
  return res.json(rec);
}
